# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kG1QrqGxtfMjYgfrGIqeKARi9bfMFBI7
"""

for i in range(1,6):

  for j in range(1,i+1):

    print(j, end="")

  print()

word = "Aishwarya"
for i in range(len(word)+1):
  print(word[:i+1])

word = "Aishwarya"
for i in range(len(word),0,-1):
  print(word[:i])

number = [1,2,3,4,5,6]
even  = [x for x in number if x % 2 == 0]
print(even)

numbers = [1,2,3,4,5,6]
new = []
for num in numbers:
  if num % 2 == 0:
    new.append(num)
print(new)

numbers = [1,2,3,4,5,6]
square_list = [x**2 for x in numbers]
print("Original List:",numbers)
print("Square List:",square_list)

numbers = [1,2,3,4,5,6]

output = [x**3 if x % 2 == 0 else x**2 for x in numbers]

print(output)

matrix = [[1,2,3],[4,5,6]]
flatten = [item for row in matrix for item in row]
print(flatten)

text = "Python Programming"

print(text)
print(type(text))

text = "Python"

print(text[0])
print(text[1])
print(text[-1])

text = "DataScience"

print(text[0:4])
print(text[4:])
print(text[:4])
print(text[-3:])
print(text[::2]) # dtsine
print(text[::-1])

#Important String Functions
#upper() & lower()
text = "Python"

print(text.upper())
print(text.lower())
#strip()
text = "   Data Analytics   "

print(text.strip())
#replace()
text = "I love Java"

print(text.replace("Java", "Python"))
#split()
text = "Python,SQL,PowerBI"

skills = text.split(",")

print(skills)
#join()
skills = ["Python", "SQL", "AI"]

result = " | ".join(skills)

print(result)
#find()
text = "Machine Learning"

print(text.find("Learning"))
#count()
text = "python python ai"

print(text.count("python"))
#startswith() & endswith()
text = "analytics.csv"

print(text.startswith("analytics"))
print(text.endswith(".csv"))
#isdigit(), isalpha(), isalnum()
print("123".isdigit())
print("Python".isalpha())
print("Python123".isalnum())
#String Programs
#Reverse String
text = "Python"

print(text[::-1])
#Palindrome Checker
text = "madam"

if text == text[::-1]:
    print("Palindrome")

else:
    print("Not Palindrome")

a="shreeshail"
print(type(a))
# var_name[start:end:step]

len(a)

a[:3]

a[3:]

a[::1]

a[::-2]

a[::2]

a[::-2]

a[::3]

a

a="shreeshail"
a.upper()

b="SHREESHAIL"
b.lower()

text = "   Data Analytics   "
text.strip()

text = "   Data Analytics   "
text.replace("Data","shree")

a="shrhs"
if a == a[::-1]:
  print("its palindro")
else:
  print("not pa")

def factorial(n):

  if n == 1:
    return 1

  return n * factorial(n-1)
n=int(input("Enter number"))
print(factorial(n))

def add_two(a,b):
  c=a+b
  return c
add_two(10,20)

def reverse(a):
   b=a[::-1]
   return b
reverse('Aishwarya')

def reverse(a):
   b=a[::-2]
   return b
reverse('Aishwarya')

def reverse(a):
   b=a[::-3]
   return b
reverse('Aishwarya')

def reverse(a):
   b=a[::-4]
   return b
reverse('Aishwarya')

try:
  a = 10
  b = 0

  print(a/b)
except ZeroDivisionError:
  print("Cannot Divide by Zero")
except ValueError:
  print("Invalid Input")
except:
  print("Something Went Wrong")

class InvalidMarksError(Exception):
  pass
Marks = -10

if Marks < 0:
    raise InvalidMarksError("Marks Cannot Be Negative")

file = open("sample.txt","w")
file.write("This is a sample text.\n")
file.write("This file was created to demonstrate error fixing.")
file.close()
file=open("sample.txt","r")
print(file)
print(file.read())
file.close()

with open("sample.txt","r") as file:
  content = file.read()
print(content)

import csv
data=[
    ["Name","Marks"],
    ["Aman",90],
    ["Priya",88]
]
with open("student.csv","w", newline="")as file:
     writer = csv.writer(file)
     writer.writerows(data)

#Real-Time Example – Banking System
class BankAccount:

    def __init__(self, name, balance):

        self.name = name
        self.balance = balance

    def deposit(self, amount):

        self.balance += amount

    def withdraw(self, amount):

        if amount <= self.balance:

            self.balance -= amount

        else:
            print("Insufficient Balance")

    def show_balance(self):

        print(self.balance)

account = BankAccount("Aman", 10000)

account.deposit(5000)

account.withdraw(3000)

account.show_balance()

import sqlite3
conn = sqlite3.connect("student.db")
print("Database Created")

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS employee (
    id INTEGER PRIMARY KEY,
    name TEXT,
    marks INTEGER,
    city TEXT,
    number INTEGER
)
""")

conn.commit()

print("Table Created")

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

query = """
INSERT INTO employee(name, salary, city, number)
VALUES (?, ?, ?, ?)
"""

cursor.execute(query, ("Aishu", 88000, "Bangalore"))

conn.commit()

print("Record Inserted")

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

employee = [
    ("Varsha", 85000, "Mumbai",9141081979),
    ("Kruthika", 92000, "Delhi",7676345352),
    ("Aishwarya", 88000, "Bangalore",8618703191)
]

query = """
INSERT INTO employee(name, salary, city, number)
VALUES (?, ?, ?,?)
"""

cursor.executemany(query, employee)

conn.commit()

print("Multiple Records Inserted")

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = sqlite3conn.cursor()

cursor.execute("SELECT * FROM employee")

rows = cursor.fetchall()

for row in rows:
    print(row)

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

cursor.execute("SELECT name * marks FROM employee")

rows = cursor.fetchall()

print(data)

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

employee = [
    ("Varsha", 85000, "Mumbai",9141081979),
    ("Kruthika", 92000, "Delhi",7676345352),
    ("Aishwarya", 88000, "Bangalore",8618703191)
]


query = """
INSERT INTO employee (name, salary, city, number)
VALUES (?, ?, ?, ?)
"""

cursor.executemany(query, employee)

conn.commit()

print("Multiple Records Inserted")

import sqlite3

conn = sqlite3.connect("employee.db")

print("Database Created")

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS employee (
    id INTEGER PRIMARY KEY,
    name TEXT,
    salary INTEGER,
    city TEXT,
    number INTEGER
)
""")

conn.commit()

print("Table Created")

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

query = """
INSERT INTO employee(name, salary, city,number)
VALUES (?, ?, ?, ?)
"""

cursor.execute(query, ("Aman", 90000, "Bangalore",5352816389))

conn.commit()

print("Record Inserted")

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

employee = [
    ("Rahul", 85000, "Mumbai", 9141081978),
    ("Priya", 920000, "Delhi", 8904549899),
    ("Kiran", 550000, "Hyderabad", 9019791979)
]

query = """
INSERT INTO employee(name, salary, city,number)
VALUES (?, ?, ?, ?)
"""

cursor.executemany(query, employee)

conn.commit()

print("Multiple Records Inserted")

import sqlite3

conn = sqlite3.connect("employee.db")

cursor = conn.cursor()

cursor.execute("SELECT * FROM employee")

rows = cursor.fetchall()

for row in rows:
    print(row)

